apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.myapp.k8s.io
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: myapp.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployment:
                  type: object
                  properties:
                    name:
                      type: string
                    image: 
                      type: string
                    replicas:
                      type: integer
                      format: int32
                service:
                  type: object
                  properties:
                    name:
                      type: string
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
  names:
    kind: App
    plural: apps
  scope: Namespaced